### PR TITLE
Handle SDL 2.23+ new versioning scheme

### LINKED ISSUE #228: Unit test expects SDL version to stay 2.0.x forever
**What doesn't work?**

`sdl2/test/version_test.py` has:

```
def test_SDL_GetVersion():
    v = sdl2.SDL_version()
    sdl2.SDL_GetVersion(ctypes.byref(v))
    assert type(v) == sdl2.SDL_version
    assert v.major == 2
    assert v.minor == 0
    assert v.patch >= 5
```

This assumes that all SDL versions compatible with SDL 2.0.0 will be versioned 2.0.x.

However, the stable version after SDL 2.0.22 is going to be 2.24.0, with prereleases identifying themselves as 2.23.x. See [the documentation](https://github.com/libsdl-org/SDL/blob/main/docs/README-versions.md) for details.

The motivation for this change was that in the previous numbering scheme, the `.0.` was essentially useless (if it only increases on incompatible changes, then it's redundant with the major version), and there was no way to signal bugfix-only releases to fix regressions or other serious bugs without adding new features.

Next time SDL breaks compatibility, the new/incompatible version will call itself SDL 3, with filenames likely to look like `libSDL3.so.0` or `SDL3.dll`.

**How To Reproduce**

Upgrade SDL2 to a git snapshot or a future stable release, then run py-sdl2's unit tests. You can see this happen in Debian's CI system when it tries to run tests against a `libsdl2` git snapshot from `experimental`, as listed in <https://ci.debian.net/packages/p/pysdl2/unstable/amd64/>:

```
self = <sdl2.test.version_test.TestSDLVersion object at 0x7fc0ba1caac0>

    def test_SDL_GetVersion(self):
        v = version.SDL_version()
        version.SDL_GetVersion(ctypes.byref(v))
        assert type(v) == version.SDL_version
        assert v.major == 2
>       assert v.minor == 0
E       assert 23 == 0
E         +23
E         -0
```

**Platform (if relevant):**
 - OS: any, tested on Debian `unstable` rolling release with a SDL git snapshot from `experimental`
 - Python Version: any, tested with 3.10.4
 - SDL2 Version: recent git snapshots (version is reported as 2.23.0 for now, a 2.23.1 development prerelease is expected in future)
 - Using pysdl2-dll: I don't think so?

### PR DESCRIPTION
**Pull request by smcv**
# PR Description

Continuation from #229. Fixes #228 (really this time).

* test: Add more realistic tests of SDL_VERSIONNUM
    
    The minor version overflows into the thousands digit in 2.23.0 and up.
    Because the major version is fixed at 2 until SDL 3 (which will be a
    separate library, like the difference between SDL 1.2 and 2), the
    numbers from here can still be used as a sort order, but are now a bit
    more confusing than they used to be.

* test: Avoid assertions that will break in upcoming versions
    
    Future SDL 2 versions are going to make more use of the minor version,
    so SDL 2.0.22, SDL_image 2.0.5, SDL_mixer 2.0.4 and SDL_ttf 2.0.18 will
    be followed by 2.24.0, 2.6.0, 2.6.0 and 2.20.0 respectively.
    
    This means assertions like version.patch >= 5 will no longer be true, so
    compare the entire version number as a tuple instead.
    
    Resolves: https://github.com/py-sdl/py-sdl2/issues/228

* dll: Represent version number as a tuple, similar to sys.version_info
    
    This avoids artificially limiting the range of possible version numbers
    that will sort correctly.
    
    For developer convenience, leave dll.version and dll.DLL.version
    working in terms of small integers, because comparisons with those are
    less verbose.

# Merge Checklist

- [ ] the PR has been reviewed and all comments are resolved
- [ ] all [CI][what-is-ci] checks pass
- [ ] (if applicable): the PR description includes the phrase `closes #<issue-number>` to [automatically close an issue][auto-close-documentation]
- [ ] (if applicable): bug fixes, new features, or [API][what-is-api] changes are documented in [news.rst][news-file]

[what-is-ci]: https://help.github.com/en/actions/building-and-testing-code-with-continuous-integration/about-continuous-integration
[auto-close-documentation]: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
[what-is-api]: https://en.wikipedia.org/wiki/Application_programming_interface
[news-file]: https://github.com/marcusva/py-sdl2/blob/master/doc/news.rst

### CODE REVIEW

**Comment by smcv** [comment]
To avoid having a gigantic diff, I haven't replaced *all* uses of `dll.version` with `version_tuple`, just one use for each library. It's fine to keep using code like `dll.version <= 2018` for old code paths, but for new code that cares about new versions, it'll be clearer to use `dll.version_tuple <= (2, 24, 1)` rather than `dll.version <= 4401`.

**Comment by smcv** [comment]
> Those version ints aren't part of the public API

`sdl2.dll.version` and `sdl2.dll.DLL.version` looked like public API to me, from the naming convention. Are they not?

**Comment by smcv** [comment]
I removed `_version_str_to_int` and `_version_int_to_str` because they were no longer needed: the only function that works with the 4-digit representation in this PR is `_version_tuple_to_int`.

I can easily put back the 2241 representation in `_version_tuple_to_int`, and we can avoid it causing problems in future by having it "saturate" at minor version 99 and micro version 9, for example:

```
_version_tuple_to_int((2, 24, 15)) == 2249
_version_tuple_to_int((2, 103, 6)) == 2999
```

(so in the unlikely event that you need to distinguish between higher numbers, *then* you have to use the tuple form). Does that make sense?

I can put back `_version_str_to_int` and `_version_int_to_str` if you want, but there won't be anything calling them any more.

**Comment by a-hurst** [comment]
That's perfect. Thanks so much!

**Pull request merged**
